# Generated by Django 2.2.3 on 2019-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('genero', models.CharField(choices=[('M', 'Masulino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=255, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=16, verbose_name='Senha')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Nome de ideia')),
                ('descricao', models.TextField(verbose_name='Descreva sua ideia')),
                ('categorias', models.CharField(choices=[('ESPORTE_RADICAL', 'Esporte Radical'), ('DESAFIANDO_A_FISICA', 'Desafiando a Física'), ('ACELERE_AO_MAXIMO', 'Extraia o Máximo de Potência do seu Motor!!!'), ('PUBLICAS', 'Públicas'), ('OUTROS', 'Outros')], max_length=255, verbose_name='Categorias')),
                ('categoria_outros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caso outros, qual?')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=None, to='website.Pessoa')),
            ],
        ),
    ]
